config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :workers
  devise_for :costumers
  devise_for :users
  resources :workers do
    collection do
      get 'skills_list'
    end
    get 'skills', on: :member
  end
  resources :costumers do
    collection do
      get 'search'
      get 'results'
    end
  end
end

app/models/concerns/searchable_skills.rb
module SearchableSkills
  extend ActiveSupport::Concern

  module ClassMethods
    def find_workers_by_skill_name(skills) # quando tenho 2 skills falha
      skill_ids = skill_ids(skills)
      worker_ids = Skilling.where(skill: skill_ids).pluck(:worker_id)
      Worker.uniq.includes(:skills).find(worker_ids)
    end

    def find_name_by_match(match)
      if match.present?
        Skill.where('name ILIKE ?', "%#{match}%")
      else
        Skill.uniq.pluck(:name)
      end
    end

    private

    def skill_ids(skills)
      return Skill.uniq.pluck(:id) unless skills.present?
      Skill.where('name ILIKE ANY ( array[?] )', sql_values(skills)).pluck(:id)
    end

    def sql_values(skills)
      skills.split(',').map { |skill| "%#{skill.strip}%" } if skills.present?
    end
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :skillings, dependent: :destroy
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/skilling.rb
class Skilling < ActiveRecord::Base
  belongs_to :skill
  belongs_to :worker

  after_destroy :remove_unused_skills

  private

  def remove_unused_skills
    skill.destroy if skill.reload.skillings.count.zero?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user/costumer.rb
class Costumer < User
  include SearchableSkills
end

app/models/user/worker.rb
class Worker < User
  include SearchableSkills
  
  has_many :skillings, dependent: :destroy
  has_many :skills, through: :skillings

  def skills_list
    skills.pluck(:name)
  end

  def skills_list=(new_skills)
    skill_names = new_skills.flatten.uniq.map(&:strip).delete_if(&:blank?)
    delete_skills(skills_list - skill_names) if skills_list.present?
    skill_names.each do |skill_name|
      skill = Skill.where(name: skill_name).first_or_create!
      skillings.where(skill: skill).first_or_create!
    end
  end

  private

  def delete_skills(skills_list)
    logger.info "DELETE: #{skills_list}"
    skills_list.each do |skill_to_delete|
      skill = Skill.where(name: skill_to_delete)
      skillings.where(skill: skill).each(&:destroy)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name,
               :email, :password, :password_confirmation, :current_password)
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:name,
               :email, :password, :password_confirmation, :current_password)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name,
               :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/costumers_controller.rb
class CostumersController < ApplicationController
  before_action :authenticate_user!

  def index
    @costumers = Costumer.all
  end

  def show
    @costumer = Costumer.find(params[:id])
    redirect_to :back, alert: 'Access denied.' unless @costumer == current_user
  end

  def search
  end

  def results
    @workers = Costumer.find_workers_by_skill_name(params[:skills])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :authenticate_user!

  def index
    @workers = Worker.all
  end

  def skills_list
    render json: Worker.find_name_by_match(params[:query])
  end

  def show
    @worker = Worker.includes(:skills).where('users.id = ?', params[:id]).first
  end

  def skills
    @worker = current_user
  end

  def update
    if current_user.update(worker_params)
      redirect_to workers_path, notice: 'Worker skills were successfully updated.'
    else
      render :skills
    end
  end

  private

  def worker_params
    params.require(:worker).permit(:name, :email, skills_list: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costumers/_costumer.html.erb
<td><%= link_to costumer.name, costumer %></td>
<td><%= link_to costumer.email, costumer %></td>

app/views/costumers/_search_bar.html.erb
<div class="row">
  <h3>Seach by skills (comma separated)</h3>
  <div class="column">
    <%= form_tag(results_costumers_path, :method => "get") do %>
    <%= text_field_tag :skills, params[:skills], placeholder: "Search Skills" %>
    <%= submit_tag "Search" %>
    <% end %>
  </div>
</div>

app/views/costumers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @costumers.each do |costumer| %>
            <tr>
              <%= render costumer %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/costumers/search.html.erb
<div class="container">
<%= render 'search_bar' %>
</div>

app/views/costumers/show.html.erb
<h3>User</h3>
<p>Name: <%= @costumer.name if @costumer.name %></p>
<p>Email: <%= @costumer.email if @costumer.email %></p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<li class="dropdown">
<a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Workers
  <span class="caret"></span>
</a>
<ul class="dropdown-menu">
  <% if worker_signed_in? %>
  <li><%= link_to 'Skills', skills_worker_path(current_worker) %></li>
  <li><%= link_to 'List workers', workers_path %></li>
  <li><%= link_to 'Edit account', edit_worker_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_worker_session_path, :method=>'delete' %></li>
  <% else %>
  <li><%= link_to 'Sign in', new_worker_session_path %></li>
  <li><%= link_to 'Sign up', new_worker_registration_path %></li>
  <% end %>
</ul>
</li>

<li class="dropdown">
<a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Costumers
  <span class="caret"></span>
</a>
<ul class="dropdown-menu">
  <% if costumer_signed_in? %>
  <li><%= link_to 'Search workers', search_costumers_path %></li>
  <li><%= link_to 'Edit account', edit_costumer_registration_path %></li>
  <li><%= link_to 'List costumers', costumers_path %></li>
  <li><%= link_to 'Sign out', destroy_costumer_session_path, :method=>'delete' %></li>
  <% else %>
  <li><%= link_to 'Sign in', new_costumer_session_path %></li>
  <li><%= link_to 'Sign up', new_costumer_registration_path %></li>
  <% end %>
</ul>
</li>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%#= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Marketplace" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Marketplace" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>A Bootstrap Starter Template</h1>
            <p class="lead">A Bootstrap HTML starter template from <a href="http://startbootstrap.com/">startbootstrap.com</a>.</p>
            <ul class="list-unstyled">
                <li>Bootstrap</li>
                <li>jQuery</li>
            </ul>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

app/views/workers/_worker.html.erb
<td><%= link_to worker.name, worker %></td>
<td><%= link_to worker.email, worker %></td>
<td>
  <% worker.skills.each do |skill| %>
  <span class="label label-default"><%= skill.name %></span>
  <% end %>
</td>

app/views/workers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @workers.each do |worker| %>
            <tr>
              <%= render worker %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/workers/show.html.erb
<h3><%= @worker.name %></h3>
<p>Email:<%= @worker.email if @worker.email %></p>
<h3>Skills:</h3>
<% @worker.skills.each do |skill| %>
<p><%= skill.name %></p>
<% end %>

app/views/workers/skills.html.erb
<h3>Edit Worker</h3>
<%= form_for(@worker) do |f| %>
<% if @worker.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@worker.errors.count, "error") %>
    prohibited this link from being saved:</h2>

  <ul>
    <% @worker.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group field">
  <%= f.label :name %><br>
  <%= f.text_field :name, autofocus: true, class: "form-control" %>
</div>

<div class="form-group field">
  <%= f.label :email %><br>
  <%= f.email_field :email %>
</div>

<div class="form-group field">
  <%= f.label :skills_list %><br>
  <%= f.select :skills_list, @worker.skills_list, {},
  {multiple: true, class: 'form-control skills-input', include_hidden: true} %>
</div>
<div class="actions">
  <%= f.submit 'Save', class: 'btn btn-default' %>
</div>
<% end %>